# Numpy

## 1. Introduction

**NumPy** stands for _**Num**erical **Py**thon_ and it's a basic package for scientific computation in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently. In this script, we will provide an overview of Numpy and introduce some features of the package Numpy.

In the following you will learn:

* How to import NumPy
* How to create multidimensional NumPy ndarrays using various methods
* How to access and change elements in ndarrays
* How to load and save ndarrays
* How to use slicing to select or change subsets of an ndarray
* Understand the difference between a view and a copy an of ndarray
* How to use Boolean indexing and set operations to select or change subsets of an ndarray
* How to sort ndarrays
* How to perform element-wise operations on ndarrays
* Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes.

## 2. Downloading NumPy
**NumPy** is included with Anaconda. If you don't already have Anaconda installed on your computer, please refer to the Anaconda section to get clear instructions on how to install Anaconda on your PC or Mac.

In [1]:
# check the version of package numpy

import numpy  # import the numpy package
print(numpy.__version__)  # print the current numpy version
# print(numpy.__doc__)  # print the brief documentation of package numpy

1.19.2


An alternative way to check which version of **NumPy** you have by typing <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">!conda list numpy</code> in your **Jupyter Notebook** or by typing <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">conda list numpy</code> in the **Anaconda prompt**. If you have another version of NumPy installed in your computer, you can degrade your version by typing <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">conda install numpy=1.13</code> in the **Anaconda prompt**. As newer versions of NumPy are released, some functions may become obsolete or replaced, so make sure you have the correct NumPy version before running the code.

In [2]:
!conda list numpy

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.19.2           py38hadc3359_0  
numpy-base                1.19.2           py38ha3acd2a_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  


## 3. NumPy Documentation
NumPy is a remarkable math library and it has many functions and features. In these introductory lessons we will only scratch the surface of what NumPy can do. If you want to explore this package and know more about NumPy, make sure you check out the NumPy Documentation:

* [NumPy Manual](https://numpy.org/doc/stable/contents.html)
* [NumPy User Guide](https://numpy.org/doc/stable/user/index.html)
* [NumPy Reference](https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html#reference)

## 4. Why Numpy?!

You may be wondering why we use NumPy. After all, Python can handle lists, as you learned in the class.

1. **Speed**

   When executing operations on large arrays, NumPy can often perform several **orders of magnitude faster** than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

2. **Array structures**

   Another great feature of NumPy is that it has **multidimensional array data structures** that can represent vectors and matrices. Nowadays, a lot of machine learning algorithms rely on matrix operations. For example, when training a Neural Network, you often have to carry out many matrix multiplications. NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

3. **Optimized built-in mathematical functions**

   Another great advantage of NumPy is that it has a large number of optimized built-in mathematical functions. These functions enable us to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.

These are just part of the key features that have made NumPy an essential package for scientific computing in Python. In fact, NumPy has become so popular that a lot of Python packages, such as Pandas, are built on top of NumPy.

In [3]:
# Example: Experience the computation speed with Numpy

import numpy as np  # import the Numpy package into Python
import time         # import the time package to calculate the command execution time

numbers = np.random.random(100000000)   # randomly generate a large list of float numbers

# Test the speed of the code to calculate the mean value
starttime = time.time()            # record the start time
mean = sum(numbers) / len(numbers) # execute the mean of the numbers
endtime = time.time()              # record the end time
print(endtime - starttime)

15.867738962173462


In [4]:
# Test the speed of the build-in mean function of Numpy
starttime = time.time()
np_mean = np.mean(numbers)
endtime = time.time()
print(endtime - starttime)

0.14168286323547363


## 5. Explore the NumPy ndarrays

At the core of NumPy is the **ndarray**, where **nd** stands for _n-dimensional_. An ndarray is a multidimensional array of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold either numbers or strings. In many Machine Learning problems you will often find yourself using ndarrays in many different ways. For instance, you might use an ndarray to hold the pixel values of an image that will be fed into a Neural Network for image classification.

But before we can dive in and start using NumPy to create ndarrays we need to import it into Python. We can import packages into Python using the **import** command and it has become a convention to import NumPy as **np**. Therefore, you can import NumPy by typing the following command in your Jupyter notebook:

<p style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px;"><code style="color:#fff;background-color:#2f3d48">import numpy as np</code></p>

In [3]:
import numpy as np

There are several ways to create ndarrays in NumPy. In the following lessons we will see two ways to create ndarrays:

1. Using regular Python lists

2. Using built-in NumPy functions

In the following, we will create ndarrays by providing Python lists to the NumPy **np.array()** function. The **np.array()** is a function that returns an **ndarray**. We should note that for the purposes of clarity, the examples throughout this section will use small and simple ndarrays. Let's start by creating 1-Dimensional (1D) ndarrays.

<!-- <p style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px;"><code style="color:#fff;background-color:#2f3d48"># import the Numpy package into Python
import numpy as np
<\br>
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])
<\br>
# Let's print the ndarray we just created using the print() command
print('x = ', x)
</code></p> -->

In [6]:
import numpy as np  # import the Numpy package into Python

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


Okay, now we introduce some useful terminology before we continue to learn. We refer to 1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. Therefore, we refer to a 2D array as a rank 2 array. Another important property of arrays is their shape. The shape of an array is the size along each of its dimensions. For example, the shape of a rank 2 array will correspond to the number of rows and columns of the array. As you will see, NumPy ndarrays have attributes that allows us to get information about them in a very intuitive way. For example, the shape of an ndarray can be obtained using the .shape attribute. The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. In the example below we will create a rank 1 array and learn how to obtain its shape, its type, and the data-type (dtype) of its elements.

In [5]:
# Practice: Create a 1D ndarray that contains only integers
import numpy as np
x = np.array([1, 2, 3, 4, 5])

# Print x
print()
print('x = ', x)
print()

# Print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


We can see that the shape attribute returns the tuple <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">(5,)</code> telling us that <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> is of rank 1 (i.e. <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> only has 1 dimension ) and it has 5 elements. The <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">type()</code> function tells us that <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> is indeed a NumPy ndarray. Finally, the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">.dtype</code> attribute tells us that the elements of <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> are stored in memory as signed *64-bit integers*. Another great advantage of NumPy is that it can handle more data-types than Python lists. You can check out all the different data types NumPy supports in the link below:

[NumPy Data Types](https://numpy.org/doc/stable/user/basics.types.html)

Another thing, ndarrays can also hold strings. Let's see how we can create a rank 1 ndarray of strings in the same manner as before, by providing the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.array()</code> function a Python list of strings.

In [7]:
# Practice: Create a rank 1 ndarray that only contains strings
import numpy as np
x = np.array(['Hello', 'World'])

# Print x
print()
print('x = ', x)
print()

# Print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['Hello' 'World']

x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


As we can see the shape attribute tells us that <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> now has only 2 elements, and even though <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> now holds strings, the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">type()</code> function tells us that <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> is still an ndarray as before. In this case however, the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">.dtype</code> attribute tells us that the elements in <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">x</code> are stored in memory as **Unicode strings of 5 characters**.

It is important to remember that one big difference between Python lists and ndarrays, is that unlike Python lists, all the elements of an ndarray must be of the same type. So, while we can create Python lists with both integers and strings, **we can't mix types in ndarrays**. If you mix different types of data in an ndarray, NumPy will interpret all elements as strings. For example,

In [8]:
# Practice: Create a rank 1 ndarray with mix types of data
x = np.array([1, 2, 'World'])

# Print the ndarray
print()
print('x = ', x)
print()

# Print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


## 6. Using Built-in Functions to Create ndarrays

There are several built-in functions in Numpy to create ndarrays:

* <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.zeros()</code>
* <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.ones()</code>
* <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.eye()</code>
* <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.diag()</code>
* <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.arange()</code>

Let's start by creating an ndarray with a specified shape that is full of zeros. We can do this by using the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.zeros()</code> function, which creates an ndarray full of zeros with the given shape. So, for example, if you wanted to create a rank 2 array with 3 rows and 4 columns, you will pass the shape to the function in the form of (rows, columns), as in the example below:

In [14]:
# Practice: Create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))  # X = np.zeros((3,4), dtype=np.float64)

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


Similarly, we can create an ndarray with a specified shape that is full of ones. We can do this by using the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.ones()</code> function. For example,

In [10]:
# Practice: Create a rank 1 ndarray with mix types of data
X = np.ones((3, 2))

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 


X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


An **Identity matrix** is a square matrix that has only 1s in its main diagonal and zeros everywhere else. The function <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.eye(N)</code> creates a square **N x N** ndarray corresponding to the Identity matrix. 

In [13]:
# Practice: Create a 5 x 5 Identity matrix. 
X = np.eye(5)

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


The <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.diag()</code> function creates an ndarray corresponding to a diagonal matrix , as shown in the example below:

In [19]:
# Practice: Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10, 20, 30, 50])

# Print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]



NumPy's <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.arange()</code> function is very versatile and can be used with either one, two, or three arguments. Below we will see examples of each case and how they are used to create different kinds of ndarrays.

1.  When used with only **one argument**, <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.arange(N)</code> will create a rank 1 ndarray with consecutive integers between **0** and **N - 1**.

In [21]:
# Practice: Create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# Print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


2. When used with **two arguments**, <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.arange(start,stop)</code> will create a rank 1 ndarray with evenly spaced values within the half-open interval <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">[start, stop)</code>. This means the evenly spaced numbers will include <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">start</code> but exclude <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">stop</code>. Let's see an example

In [22]:
# Practice: Create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4, 10)

# Print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


Even though the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.arange()</code> function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.linspace()</code>. The <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.linspace(start, stop, N)</code> function returns <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">N</code> evenly spaced numbers over the closed interval <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">[start, stop]</code>. This means that both the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">start</code> and the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">stop</code> values are included.

In [23]:
# Practice: Create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0, 25, 10)

# Print the ndarray
print()
print('x = \n', x)
print()

# Print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


However, you can let the endpoint of the interval be excluded (just like in the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.arange()</code> function) by setting the keyword <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">endpoint = False</code> in the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.linspace()</code> function.

In [3]:
# Practice: Create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
x = np.linspace(0, 25, 10, endpoint=False)
y = np.linspace(0, 25, 10)  # for comparison

# Print the ndarray
print()
print('x = ', x)
print('y = ', y)
print()

# Print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
y =  [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


As we can see, because we have excluded the endpoint, the spacing between values had to change in order to fit 10 evenly spaced numbers in the given interval.

we can use these functions to create rank 2 ndarrays of any shape by combining them with the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.reshape()</code> function. The <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.reshape(ndarray, new_shape)</code> function converts the given **ndarray** into the specified **new_shape**. It is important to note that the **new_shape** should be compatible with the number of elements in the given **ndarray**. For example, you can convert a rank 1 ndarray with 6 elements, into a 3 x 2 rank 2 ndarray, or a 2 x 3 rank 2 ndarray, since both of these rank 2 arrays will have a total of 6 elements. However, you can't reshape the rank 1 ndarray with 6 elements into a 3 x 3 rank 2 ndarray, since this rank 2 array will have 9 elements, which is greater than the number of elements in the original ndarray. Let's see some examples:

In [7]:
# Create a rank 1 ndarray with 6 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 3 x 2 ndarray.
X = np.linspace(0, 50, 6, endpoint=False).reshape(3, 2)

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[ 0.          8.33333333]
 [16.66666667 25.        ]
 [33.33333333 41.66666667]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [9]:
# or you can also do the same thing with the separate steps

# 1. Create a rank 1 ndarray with 6 integers evenly spaced between 0 and 50.
X = np.linspace(0, 50, 6, endpoint=False)

# 2. reshape it to a 3 x 2 ndarray.
X = X.reshape(3, 2)

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[ 0.          8.33333333]
 [16.66666667 25.        ]
 [33.33333333 41.66666667]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


The last type of ndarrays we are going to create are **random ndarrays**. Random ndarrays are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing the weights of a Neural Network. NumPy offers a variety of random functions to help us create random ndarrays of any shape.

Let's start by using the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.random.random(shape)</code> function to create an ndarray of the given **shape** with random floats in the half-open interval [0.0, 1.0).

In [10]:
# Create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.9600085  0.7605599  0.56870815]
 [0.57986603 0.33160919 0.41341585]
 [0.75222526 0.40316381 0.98835291]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


NumPy also allows us to create ndarrays with random integers within a particular interval. The function <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">np.random.randint(start, stop, size = shape)</code> creates an ndarray of the given **shape** with random integers in the half-open interval **[start, stop)**. Let's see an example:

In [11]:
# Create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# Print X
print()
print('X = \n', X)
print()

# Print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[11 10]
 [ 6  8]
 [ 6 10]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create random ndarrays with numbers drawn from various probability distributions. The function np.random.normal(mean, standard deviation, size=shape), for example, creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard deviation. Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

## 7. Accessing, Deleting, and Inserting Elements Into ndarrays

We will now see how NumPy allows us to effectively manipulate the data within the ndarrays. NumPy ndarrays are **mutable**, meaning that the elements in ndarrays can be changed after the ndarray has been created. NumPy ndarrays can also be **sliced**, which means that ndarrays can be split in many different ways. This allows us, for example, to retrieve any subset of the ndarray that we want. Often in Machine Learning you will use slicing to separate data, as for example when dividing a data set into training, cross validation, and testing sets.

We will start by looking at how the elements of an ndarray can be **accessed** or modified by **indexing**. Elements can be accessed using indices inside square brackets, <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">[ ]</code>. NumPy allows you to use both positive and negative indices to access elements in the ndarray. Positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array. Let's see how we can access elements in rank 1 ndarrays:

In [14]:
# Create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# Print x
print()
print('x = ', x)
print()

# Access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


Notice that to access the first element in the ndarray we have to use the index 0 not 1. Also notice, that the same element can be accessed using both positive and negative indices. As mentioned earlier, positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array.

Now let's see how we can change the elements in rank 1 ndarrays. We do this by accessing the element we want to change and then using the <code style="color:#fff;background-color:#2f3d48;border-radius: 4px;border: 1px solid #737b83;padding: 2px 4px">=</code> sign to assign the new value:

In [15]:
# Create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# Print the original x
print()
print('Original:\n x = ', x)
print()

# Change the fourth element in x from 4 to 20
x[3] = 20

# Print x after it was modified 
print('Modified:\n x = ', x)


Original:
 x =  [1 2 3 4 5]

Modified:
 x =  [ 1  2  3 20  5]
